config/routes.rb
LoveMaybe::Application.routes.draw do
  
  resources :friend_sayings

  resources :yes_sayings

  resources :date_responses

  resources :date_requests, only: [:create, :destroy, :edit, :update, :new]

  resources :user_dating_usernames

   get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  post 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/failure', to: redirect('/')

  delete '/signout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  get '/responses', to: 'welcome#response_tab'

  resources :users, except: [:show, :edit]

  resources :users, path: "", only: [:show, :edit]

  resources :sessions, only: [:new, :create, :destroy]	

  resources :password_resets

  resources :email_confirms

 

  root 'welcome#index'

end

app/models/user_dating_username.rb
class UserDatingUsername < ActiveRecord::Base
	belongs_to :user
	before_validation :set_uniq_username

	validates :dating_site_website, :inclusion => {:in => ['OkCupid', 'Tinder', 'eHarmony', 'Match.com', 'PlentyofFish', 'Zoosk', 'Christian Mingle', 'DateHookup', 'HowAboutWe', 'Coffee Meets Bagel', 'BlackPeopleMeet', 'JDate', 'Badoo', 'Meetme', 'Skout', 'SeniorPeopleMeet']}, allow_blank: true
	validates_uniqueness_of :uniq_username, allow_nil: true, allow_blank: true, message: "- We're sorry, but a profile with that dating site username already exists."
	validate :check_username_site_presence

	def check_username_site_presence
		if ! self.dating_site_username.blank? || ! self.dating_site_website.blank?
			if self.dating_site_username.blank? || self.dating_site_website.blank?
				errors.add(:dating_site_username, "must provide both username and site")
			end
		end
	end

	def set_uniq_username
		if ! self.dating_site_username.blank? && ! self.dating_site_website.blank?
			self.uniq_username = "#{self.dating_site_username}-#{self.dating_site_website}"
		end
	end
end

app/controllers/user_dating_usernames_controller.rb
class UserDatingUsernamesController < ApplicationController
  before_action :set_user_dating_username, only: [:show, :edit, :update, :destroy]

  # GET /user_dating_usernames
  # GET /user_dating_usernames.json
  def index
    @user_dating_usernames = UserDatingUsername.all
  end

  # GET /user_dating_usernames/1
  # GET /user_dating_usernames/1.json
  def show
  end

  # GET /user_dating_usernames/new
  def new
    @user_dating_username = UserDatingUsername.new
  end

  # GET /user_dating_usernames/1/edit
  def edit
  end

  # POST /user_dating_usernames
  # POST /user_dating_usernames.json
  def create
    @user_dating_username = UserDatingUsername.new(user_dating_username_params)

    respond_to do |format|
      if @user_dating_username.save
        format.html { redirect_to @user_dating_username, notice: 'User dating username was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_dating_username }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_dating_username.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_dating_usernames/1
  # PATCH/PUT /user_dating_usernames/1.json
  def update
    respond_to do |format|
      if @user_dating_username.update(user_dating_username_params)
        format.html { redirect_to @user_dating_username, notice: 'User dating username was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_dating_username.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_dating_usernames/1
  # DELETE /user_dating_usernames/1.json
  def destroy
    @user_dating_username.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_path(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_dating_username
      @user_dating_username = UserDatingUsername.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_dating_username_params
      params.require(:user_dating_username).permit(:dating_site_id, :user_id, :dating_site_username, :dating_site_website, :uniq_username)
    end
end

app/helpers/user_dating_usernames_helper.rb
module UserDatingUsernamesHelper
end

app/views/user_dating_usernames/_form.html.erb
<%= form_for(@user_dating_username) do |f| %>
  <% if @user_dating_username.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_dating_username.errors.count, "error") %> prohibited this user_dating_username from being saved:</h2>

      <ul>
      <% @user_dating_username.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dating_site_id %><br>
    <%= f.number_field :dating_site_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :dating_site_username %><br>
    <%= f.text_field :dating_site_username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_dating_usernames/edit.html.erb
<h1>Editing user_dating_username</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_dating_username %> |
<%= link_to 'Back', user_dating_usernames_path %>

app/views/user_dating_usernames/index.html.erb
<h1>Listing user_dating_usernames</h1>

<table>
  <thead>
    <tr>
      <th>Dating site</th>
      <th>User</th>
      <th>Dating site username</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_dating_usernames.each do |user_dating_username| %>
      <tr>
        <td><%= user_dating_username.dating_site_id %></td>
        <td><%= user_dating_username.user_id %></td>
        <td><%= user_dating_username.dating_site_username %></td>
        <td><%= link_to 'Show', user_dating_username %></td>
        <td><%= link_to 'Edit', edit_user_dating_username_path(user_dating_username) %></td>
        <td><%= link_to 'Destroy', user_dating_username, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User dating username', new_user_dating_username_path %>

app/views/user_dating_usernames/new.html.erb
<h1>New user_dating_username</h1>

<%= render 'form' %>

<%= link_to 'Back', user_dating_usernames_path %>

app/views/user_dating_usernames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dating site:</strong>
  <%= @user_dating_username.dating_site_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_dating_username.user_id %>
</p>

<p>
  <strong>Dating site username:</strong>
  <%= @user_dating_username.dating_site_username %>
</p>

<%= link_to 'Edit', edit_user_dating_username_path(@user_dating_username) %> |
<%= link_to 'Back', user_dating_usernames_path %>