config/routes.rb
LoveMaybe::Application.routes.draw do
  
  resources :friend_sayings

  resources :yes_sayings

  resources :date_responses

  resources :date_requests, only: [:create, :destroy, :edit, :update, :new]

  resources :user_dating_usernames

   get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  post 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/failure', to: redirect('/')

  delete '/signout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  get '/responses', to: 'welcome#response_tab'

  resources :users, except: [:show, :edit]

  resources :users, path: "", only: [:show, :edit]

  resources :sessions, only: [:new, :create, :destroy]	

  resources :password_resets

  resources :email_confirms

 

  root 'welcome#index'

end

app/models/date_request.rb
class DateRequest < ActiveRecord::Base
	belongs_to :user
	has_many :date_responses

	validates :date_phone, length: { minimum: 14, maximum: 14, message: "Phone must be valid (999) 999-9999 format" }, uniqueness: { case_sensitive: false, message: "You can't have multiple dates with the same phone number" }, allow_blank: true, allow_nil: true
	validates :date_rating, presence: {message: "What did you think of the date?!"}
	validates :date_comment, presence: {message: "Comment can't be blank"}
	validates :first_name, presence: {message: "Must provide first name"}
	validate :check_for_phone_or_username, on: :create

	def check_for_phone_or_username
		if ! date_username.blank? || ! date_username_site.blank?
			if date_username.blank? || date_username_site.blank?
				errors.add(:date_username, "Must provide both date username and site")
			end
		end

		if date_phone.blank?
			if date_username.blank? || date_username_site.blank?
				errors.add(:date_username, "Date username/site information must be provided if you do not provide phone number")
			end
			previous_requests = DateRequest.where("user_id = ?", self.user_id)
			previous_requests.each do |request|
				if request.date_username == self.date_username && request.date_username_site == self.date_username_site && ! self.date_username.blank?
					errors.add(:date_username, "We're sorry. You have already added a date matching the information provided.")
				end
			end
		end
	end
end

app/controllers/date_requests_controller.rb
class DateRequestsController < ApplicationController
  before_action :set_date_request, only: [:show, :edit, :update, :destroy]
  before_filter :load
  before_action :check_if_admin, only: [:index, :show]

  def load
    @date_requests = DateRequest.all
  end


  # GET /date_requests
  # GET /date_requests.json
  def index
    @date_requests = DateRequest.all
  end

  def new
	  @date_request = DateRequest.new
	  
	  respond_to do |format|
		  format.html
		  format.js
	  end

  end

  # GET /date_requests/1
  # GET /date_requests/1.json
  def show
  end


  # GET /date_requests/1/edit
  def edit
  end

  # POST /date_requests
  # POST /date_requests.json
  def create
	@user = current_user  
    @date_request = current_user.date_requests.new(date_request_params)

    respond_to do |format|
      if @date_request.save

	format.js { render action: 'create_success' }
      
	format.html { redirect_to root_url }
        format.json { render action: 'show', status: :created, location: @date_request }
      else
	format.js { }
        format.html { render action: 'new' }
        format.json { render json: @date_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /date_requests/1
  # PATCH/PUT /date_requests/1.json
  def update
    respond_to do |format|
      if @date_request.update(date_request_params)
        format.html { redirect_to root_path, notice: 'Date request was successfully updated.' }
        format.json { head :no_content }
      else
	format.js { }
        format.html { render action: 'edit' }
        format.json { render json: @date_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /date_requests/1
  # DELETE /date_requests/1.json
  def destroy
    @date_request.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_request
      @date_request = DateRequest.find(params[:id])
    end

    def check_if_admin
	    redirect_to root_path unless current_user.admin?

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def date_request_params
      params.require(:date_request).permit(:user_id, :first_name, :last_name, :date_phone, :date_username, :date_username_site, :date_comment, :date_rating)
    end
end

app/helpers/date_requests_helper.rb
module DateRequestsHelper
end

app/views/date_requests/_form.html.erb
<%= form_for(@date_request) do |f| %>
  <% if @date_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@date_request.errors.count, "error") %> prohibited this date_request from being saved:</h2>

      <ul>
      <% @date_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="large-12" style="margin-top: 15px;">

  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :date_phone %><br>
    <%= f.number_field :date_phone %>
  </div>
  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :date_username %><br>
    <%= f.text_field :date_username %>
  </div>
  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :date_username_site %><br>
    <%= f.select( :date_username_site, [['OkCupid','OkCupid'],['Tinder','Tinder'],['eHarmony','eHarmony'],['Match.com','Match.com'],['PlentyofFish','PlentyofFish'],['Zoosk','Zoosk'],['Christian Mingle','Christian Mingle'],['DateHookup','DateHookup'],['HowAboutWe','HowAboutWe'],['Coffee Meets Bagel','Coffee Meets Bagel'],['BlackPeopleMeet','BlackPeopleMeet'],['JDate','JDate'],['Badoo','Badoo'],['Meetme','Meetme'],['Skout','Skout'],['SeniorPeopleMeet','SeniorPeopleMeet']], { :prompt => 'Select'}, style: "height: 32px;") %>
  </div>
  <div class="large-2 field" style="display: inline-block;">
    <%= f.label :date_rating %><br>
    <%= f.text_field :date_rating %>
  </div>
  <div class="field">
    <%= f.label :date_comment %><br>
    <%= f.text_area :date_comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/date_requests/create.js.erb
$("#date_request_area").html("<%= escape_javascript(render('shared/date_request_form')) %>")

app/views/date_requests/create_success.js.erb
$(":input:not(input[type=submit])").val("");
$("#date_request_area").hide(300);
$("#request_area").html("<%= escape_javascript(render('welcome/index')) %>")

app/views/date_requests/edit.js.erb
$("#date_request_area").html("<%= escape_javascript(render('shared/edit_date_request_form')) %>")

app/views/date_requests/index.html.erb
<h1>Listing date_requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Date phone</th>
      <th>Date username</th>
      <th>Date username site</th>
      <th>Date comment</th>
      <th>Date rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @date_requests.each do |date_request| %>
      <tr>
        <td><%= date_request.user_id %></td>
        <td><%= date_request.first_name %></td>
        <td><%= date_request.last_name %></td>
        <td><%= date_request.date_phone %></td>
        <td><%= date_request.date_username %></td>
        <td><%= date_request.date_username_site %></td>
        <td><%= date_request.date_comment %></td>
        <td><%= date_request.date_rating %></td>
        <td><%= link_to 'Show', date_request %></td>
        <td><%= link_to 'Edit', edit_date_request_path(date_request), remote: :true, class: "button small", id: "home-edit-date-button" %></td>
        <td><%= link_to 'Destroy', date_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Date request', new_date_request_path %>

app/views/date_requests/new.js.erb
$("#date_request_area").html("<%= escape_javascript(render('shared/date_request_form')) %>")

app/views/date_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @date_request.user_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @date_request.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @date_request.last_name %>
</p>

<p>
  <strong>Date phone:</strong>
  <%= @date_request.date_phone %>
</p>

<p>
  <strong>Date username:</strong>
  <%= @date_request.date_username %>
</p>

<p>
  <strong>Date username site:</strong>
  <%= @date_request.date_username_site %>
</p>

<p>
  <strong>Date comment:</strong>
  <%= @date_request.date_comment %>
</p>

<p>
  <strong>Date rating:</strong>
  <%= @date_request.date_rating %>
</p>

<%= link_to 'Edit', edit_date_request_path(@date_request) %> |
<%= link_to 'Back', date_requests_path %>

app/views/date_requests/update.js.erb
$("#date_request_area").html("<%= escape_javascript(render('shared/edit_date_request_form')) %>")