config/routes.rb
LoveMaybe::Application.routes.draw do
  
  resources :friend_sayings

  resources :yes_sayings

  resources :date_responses

  resources :date_requests, only: [:create, :destroy, :edit, :update, :new]

  resources :user_dating_usernames

   get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  post 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/failure', to: redirect('/')

  delete '/signout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  get '/responses', to: 'welcome#response_tab'

  resources :users, except: [:show, :edit]

  resources :users, path: "", only: [:show, :edit]

  resources :sessions, only: [:new, :create, :destroy]	

  resources :password_resets

  resources :email_confirms

 

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password, :password_confirmation

	mount_uploader :image, ImageUploader

	has_many :user_dating_usernames, dependent: :destroy
	has_many :date_requests, dependent: :destroy
	has_many :date_responses, through: :date_requests
	accepts_nested_attributes_for :user_dating_usernames, :allow_destroy => true	
	VALID_HANDLE_REGEX = /\A([!#$&-;=?-\[\]_a-z~]|%[0-9a-fA-F]{2})+\z/
	validates :user_handle, presence: true, length: { maximum: 250 }, format: {with: VALID_HANDLE_REGEX}, uniqueness: { case_sensitive: false }, exclusion: {in: %w[signup signin signout contact responses]}
	validates :url_slug, presence: true, length: { maximum: 250 }, uniqueness: { case_sensitive: false }, exclusion: {in: %w[signup signin signout contact responses response_tab terms privacy users date_requests date_responses]}
	validates :first_name, presence: true, length: { maximum: 75 }
	validates :last_name, presence: true, length: { maximum: 75 }

	# still need to do whole (312) 343-2234 format thing BE and FE
	validates :user_phone, length: { minimum: 14, maximum: 14, message: "must be valid (999) 999-9999 format" }, allow_nil: true, allow_blank: true
	validates_uniqueness_of :user_phone, :allow_nil => true, :allow_blank => true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 6 }, :if => :password_digest_changed? && :should_validate_password?
	validates :password_confirmation, presence: true,:if => :password_digest_changed? && :should_validate_password?

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token
	validates_confirmation_of :password, :if => :password_digest_changed? && :should_validate_password?

	before_validation :generate_slug

	after_create :send_email_confirm

	
	def to_param
		url_slug
	end

	def generate_slug
		self.url_slug = user_handle.parameterize
	end
	
	def password=(unencrypted_password)
	    require "bcrypt"
	    @password = unencrypted_password
	    cost = BCrypt::Engine::DEFAULT_COST
	    self.password_digest = BCrypt::Password.create(unencrypted_password, cost: cost)
	end

	def password_confirmation=(unencrypted_password)
	    unless unencrypted_password.blank?
		    @password_confirmation = unencrypted_password
	    end
	end

	 def authenticate(unencrypted_password)
	    require "bcrypt"
        BCrypt::Password.new(password_digest) == unencrypted_password && self
	 end

	 def create_remember_token
	  self.remember_token = SecureRandom.urlsafe_base64
	 end

	 def send_password_reset
		 generate_token(:password_reset_token)
		 self.password_reset_sent_at = Time.zone.now
		 save!
		 UserMailer.password_reset(self).deliver
	 end

	 def send_email_confirm
		 generate_token(:email_confirm_token)
		 self.email_confirm_sent_at = Time.zone.now
		 save!
		 UserMailer.email_confirm(self).deliver
	 end

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end

	def from_omniauth(auth)
		    self.provider = auth.provider
		    self.uid = auth.uid
		    self.first_name = auth.info.first_name
		    self.last_name = auth.info.last_name
		    self.email = auth.info.email 
		    self.fb_image = auth.info.image
		    self.fb_location = auth.info.location
		    self.oauth_token = auth.credentials.token
		    self.oauth_expires_at = Time.at(auth.credentials.expires_at)
		    self.fb_verified = auth.verified
		    if ! auth.info.nickname.nil?
			    self.user_handle = auth.info.nickname
		    else
			    self.user_handle = auth.extra.raw_info.id
		    end
    	end
	 


	 def should_validate_password?
	    if self.password_digest.present?
		    false
	    elsif self.provider.present? && self.uid.present?
		    false
	    else
		    true
	    end
	 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_signed_in, only: [:new]

  # GET /users
  # GET /users.json
  def index
	  redirect_to root_path unless current_user.admin?
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
	  
	  session[:your_response] = nil
	  session[:request] = nil
	  
  end

  # GET /users/new
  def new
    @user = User.new
    @user.user_dating_usernames.build
  end

  # GET /users/1/edit
  def edit
	  redirect_to root_path unless signed_in? && @user == current_user || current_user.admin?
		 

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
	      @user.user_dating_usernames.each {|name| name.destroy unless name.dating_site_username.length > 0 }
	      sign_in @user
        format.html { redirect_to root_path, notice: 'Welcome to LoveMeMaybe!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
	      @user.user_dating_usernames.each {|name| name.destroy unless name.dating_site_username.length > 0 }

	  cookies.permanent[:remember_token] = @user.remember_token


        format.html { redirect_to root_url+@user.url_slug, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_url_slug!(params[:id])
    end

    def check_signed_in
	    if signed_in?
		    redirect_to root_path
	    end
    end


    def check_user_edit
	    
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :city, :state, :hide_city_state, :receive_notifications, :email, :user_phone, :user_handle, :image, :admin, :profile_name_hidden, :password_digest, :password_reset_token, :password_reset_sent_at, :remember_token, :email_confirm_token, :email_confirm_sent_at, :email_confirmed, :password, :password_confirmation, user_dating_usernames_attributes: [:dating_site_username, :dating_site_website])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" style="background: #F5A0A0;border: 1px solid;margin-bottom: 25px;padding: 10px;">
      <h5 style="margin-bottom: 0px;"><%= pluralize(@user.errors.count, "error") %> prohibited you from updating your profile:</h5>

      <ul style="padding: 0 0 0 30px;margin-bottom: 5px;">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="large-12" >
	  <div class="large-4" style="float: right; display: inline-block;">
	<p style="font-size: 18px;"><strong>Note:</strong> any information provided remains secure and strictly confidential, and it will only be used to match you with individuals you have dated.</p>
</div>


<div class="large-8" style="display: inline-block;">

<% if @user.image? %>
			<div class="large-2" style="height:150px;width: 150px;float:left;margin-top:22px;"><%= image_tag @user.image_url(:thumb), style: "box-shadow: 0px 0px 0px 2.5px;"%></div>
			<% else %>

				<div class="large-2" style="height:150px;width: 150px;;float:left;margin-top:22px;"><%= image_tag('profile-picture-holder.png', style: "box-shadow: 0px 0px 0px 2.5px;") %></div>
			<% end %>
			<div style="clear:both;"></div>

  <div class="large-5 field" style="display: block; margin-right: 10px;margin-bottom: 15px;">
    <%= f.label :image, "Profile Picture" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
    <%= f.label :first_name, "First Name*" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="large-5 field" style="display: inline-block;">
    <%= f.label :last_name, "Last Name*" %><br>
    <%= f.text_field :last_name %>
  </div>
 
  <div style="clear:both;"></div>
  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
	  <%= f.label :email, "Email*" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="large-5 field" style="display: inline-block;">
    <%= f.label :user_phone, "Phone Number (optional)" %><br>
    <%= f.text_field :user_phone, {id: "phone_new"} %>
  </div>
  <div style="clear:both;"></div>

  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
    <%= f.label :city, "City" %><br>
    <%= f.text_field :city %>
  </div>
  <div class="large-5 field" style="display: inline-block;">
    <%= f.label :state, "State" %><br>
    <%= f.text_field :state %>
  </div>
  <div class="large-6 field" style="display: inline-block; margin-top: 10px;">
	  <%= f.label :user_handle, "LoveMeMaybe Handle*", style: "display: inline-block; margin-bottom:5px;" %>
	  <br>
	  <%= f.label :user_handle, "(This will be your unique LoveMeMaybe page)", style: "display: inline-block; margin-bottom:10px;font-size: 12px;" %>
	  <br>
    <%= f.text_field :user_handle %>
  </div>
 
  <div style="clear:both;"></div>

  <h4>Online Dating Usernames</h4>

  <% @user.user_dating_usernames.each do |name|%>

	  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
<span style="-webkit-appearance: none;
	-webkit-border-radius: 0;
	width: 100%;
border-radius: 0;
background-color: white;
font-family: inherit;
border: 1px solid #cccccc;
-webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
color: rgba(0, 0, 0, 0.75);
font-size: 0.875em;
display:inline-block;
margin: 0 10px 1em 0;
padding: 0.5em;
-moz-box-sizing: border-box;
-webkit-box-sizing: border-box;
box-sizing: border-box;
-webkit-transition: -webkit-box-shadow 0.45s, border-color 0.45s ease-in-out;
-moz-transition: -moz-box-shadow 0.45s, border-color 0.45s ease-in-out;
transition: box-shadow 0.45s, border-color 0.45s ease-in-out;"> <%= name.dating_site_username %></span>
		  </div>
  <div class="large-5 field" style="display: inline-block; ">
<span style=" -webkit-appearance: none;
	  -webkit-border-radius: 0;
border-radius: 0;
background-color: white;
font-family: inherit;
border: 1px solid #cccccc;
-webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
color: rgba(0, 0, 0, 0.75);
display:inline-block;
width: 100%;
font-size: 0.875em;
margin: 0 0 1em 0;
padding: 0.5em;
-moz-box-sizing: border-box;
-webkit-box-sizing: border-box;
box-sizing: border-box;
-webkit-transition: -webkit-box-shadow 0.45s, border-color 0.45s ease-in-out;
-moz-transition: -moz-box-shadow 0.45s, border-color 0.45s ease-in-out;
transition: box-shadow 0.45s, border-color 0.45s ease-in-out;"><%= name.dating_site_website %></span>
		  </div>
		  <div class="field" style="width: 5%; display: inline-block; padding-top:9px;">
		  <%= link_to 'Delete', name.id ? name : edit_user_path(current_user), style: 'margin: 10px 0 0 10px;',  method: name.id ? :delete : :get, data: { confirm: 'Are you sure?' } %>
	  </div>
	   <div style="clear:both;"></div>

		 
	  <% end %>
	  <%= link_to_add_fields "Add Another Username +", f, :user_dating_usernames %>
	  

  <div style="clear:both;"></div>
  <h4>Privacy Settings</h4>
   <div class="large-6 field" style="display: inline-block; margin-bottom:10px;">
	   <%= f.check_box :profile_name_hidden, style:"float:left; margin-right:5px;" %>
	   <%= f.label :profile_name_hidden, "Hide Name on Public Profile?" %> <br>
	   <%= f.check_box :hide_city_state, style:"float:left; margin-right:5px;" %>
	   <%= f.label :hide_city_state, "Hide City/State on Public Profile?" %>
    
  </div>

  <div style="clear:both;"></div>

  <h4>Notifications</h4>
   <div class="large-6 field" style="display: inline-block; margin-bottom:10px;">
	   <%= f.check_box :receive_notifications, style:"float:left; margin-right:5px;" %>
	   <%= f.label :receive_notifications, "Receive notification if a date responds?" %> 
    
  </div>

  <div style="clear:both;"></div>
  
  <div class="actions">
    <%= f.submit 'Update', class: "button" %>
  </div>
  </div>
<% end %>



  </div>

app/views/users/_form.html.erb
<script>
  $(function() {
    $( document ).tooltip();
  });
  </script>


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" style="background: #F5A0A0;border: 1px solid;margin-bottom: 25px;padding: 10px;">
      <h5 style="margin-bottom: 0px;"><%= pluralize(@user.errors.count, "error") %> prohibited you from signing up:</h5>

      <ul style="padding: 0 0 0 30px;margin-bottom: 5px;">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="large-12" >
	  <div class="large-4" style="float: right; display: inline-block;">
	<p style="font-size: 18px;"><strong>Note:</strong> any information provided remains secure and strictly confidential, and it will only be used to match you with individuals you have dated.</p>
  </div>
	<div class="large-8" style="display: inline-block;">
  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
    <%= f.label :first_name, "First Name*" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="large-5 field" style="display: inline-block;">
    <%= f.label :last_name, "Last Name*" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div style="clear:both;"></div>
  <div class="large-5 field" style="display: inline-block; margin-right: 10px;">
	  <%= f.label :email, "Email*" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="large-5 field" style="display: inline-block;">
    <%= f.label :user_phone, "Phone Number (optional)" %><br>
    <%= f.text_field :user_phone, {id: "phone_new"} %>
  </div>
  <div style="clear:both;"></div>

	  <%= f.fields_for :user_dating_usernames do |builder| %>
		  <%= render 'user_dating_username_fields', f: builder %>
	  <% end %>
	  <%= link_to_add_fields("Add Dating Username +", f, :user_dating_usernames) %>
	  

  <div style="clear:both;"></div>
  <div class="large-6 field" style="display: inline-block; margin-top: 10px;">
	  <%= f.label :user_handle, "LoveMeMaybe Handle*", style: "display: inline-block; margin-bottom:5px;" %>
	  <br>
	  <%= f.label :user_handle, "(This will be your unique LoveMeMaybe page)", style: "display: inline-block; margin-bottom:10px;font-size: 12px;" %>
	  <br>
    <%= f.text_field :user_handle %>
  </div>
  <div style="clear:both;"></div>
  <div class="large-6 field" style="display: inline-block;">
    <%= f.label :password, "Password (minimum 6 characters)*" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="large-6 field" style="display: inline-block;">
    <%= f.label :password_confirmation, "Password Confirmation*" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div style="clear:both;"></div>
  <div class="actions">
    <%= f.submit 'Sign Up', class: "button" %>
  </div>
  </div>
<% end %>



  </div>

app/views/users/_response_area.html.erb
		<% if ! @date_response.nil? %>
			<% if ! @date_request.nil? %>
				<% if @date_request.date_rating == @date_response.date_response_rating %>
					<% if @date_request.date_rating != 'No' %>
						<h3 style="margin-bottom: 40px;">You and <%=@user.user_handle%> both want to <%= @date_request.date_rating == 'Yes' ? 'go on another date!' : 'be friends!' %></h3>
						<h5 style="font-weight: 300;">What <%= @user.user_handle %> said about you:</h5>
						<h5 style="color: #2795b6; font-style: italic;margin-bottom: 40px;"><%= @date_request.date_comment %></h5>
						<h3 style="margin-bottom: 40px;"><%= @date_request.date_rating == 'Yes' ? YesSaying.first(offset: rand(YesSaying.count)).saying : FriendSaying.first(offset: rand(FriendSaying.count)).saying %></h3>
						<div class="large-10" style="margin: 65px auto 0 auto;"><span style=" margin: 0 auto 10px auto;display: block;">Want to see how it went with other dates? </span><%=link_to current_user.nil? ? "Sign up!" : "Add Dates +", current_user.nil? ? signup_path : root_path, class: "button small", style: "margin-bottom: 15px;" %></div>

					<% else %>
						<h3 style="margin-bottom: 40px;">Looks like you and <%=@user.user_handle%> both just want to move on.</h3><h5 style="font-weight:normal;"> Don't worry, your message will remain anonymous and will only be visible if <%=@user.user_handle%> has at least 3 anonymous messages. </h5>
						<div class="large-10" style="margin: 65px auto 0 auto;"><span style=" margin: 0 auto 10px auto;display: block;">Want to see how it went with other dates? </span><%=link_to current_user.nil? ? "Sign up!" : "Add Dates +", current_user.nil? ? signup_path : root_path, class: "button small", style: "margin-bottom: 15px;" %></div>
					<% end %>
				<% else %>
					<h3 style="margin-bottom: 40px;">Awww, we're sorry. You and <%=@user.user_handle%> don't want the same thing.</h3><h5 style="font-weight:normal;">Don't worry, your message will remain anonymous and will only be visible if <%=@user.user_handle%> has at least 5 anonymous messages. </h5>
					<div class="large-10" style="margin: 65px auto 0 auto;"><span style=" margin: 0 auto 10px auto;display: block;">Want to see how it went with other dates? </span><%=link_to current_user.nil? ? "Sign up!" : "Add Dates +", current_user.nil? ? signup_path : root_path, class: "button small", style: "margin-bottom: 15px;" %></div>
				<% end %>
			<% else %>
				<h3 style="margin-bottom: 40px;">Oops! Looks like <%=@user.user_handle%> hasn't added you as a past date.</h3>
				<div class="large-10" style="margin: 65px auto 0 auto;"><span style=" margin: 0 auto 10px auto;display: block;">Want to see what <%=@user.user_handle%> thought of your date or see how it went with your other dates? </span><%=link_to "Sign up!", signup_path, class: "button small", style: "margin-bottom: 15px;" %></div>
				<% end %>
			<% else %>

				



				<h3 style="margin-bottom: 40px;">Find out if <%=@user.user_handle%> wants to go out again or be friends.</h3>
				<h5 style="font-weight:normal;">Have you been on a date with <%=@user.user_handle%>?</h5>
				<%= link_to 'YES', new_date_response_path(user_id: @user.id), remote: :true, class: "button success tiny", style: "margin: 3px;width: 70px;height: 32px;border-radius: 4px;padding: 7px;font-size: 14px;" %>
				<a href=<%=root_path%> class="button alert tiny" style="margin: 3px;width: 70px;height: 32px;border-radius: 4px;padding: 7px;font-size: 14px;">NO</a>	
				<h5 style="font-weight:normal;margin-top: 25px;">Don't worry! If you didn't like <%=@user.user_handle%>, or if you want different things, then your response will be aggregated with others to remain anonymous</h5>

				<div class="large-10" style="margin: 65px auto 0 auto;"><span style=" margin: 0 auto 10px auto;display: block;">Want to know about your other dates? </span><%=link_to "Sign up!", signup_path, class: "button small", style: "margin-bottom: 15px;" %></div>
				<% end %>

app/views/users/_user_dating_username_fields.html.erb
<div class="fieldset">
		<div class="large-5 field" style="display: inline-block; margin-right: 10px;">
			  <%= f.label :dating_site_username, "Online Dating Username" %>
			  <%= f.text_field :dating_site_username %>
		  </div>
		  <div class="large-5 field" style="display: inline-block;">
			  <%= f.label :dating_site_website, "Online Dating Site/App" %>
			  <%= f.select( :dating_site_website, [['OkCupid','OkCupid'],['eHarmony','eHarmony'],['Match.com','Match.com'],['PlentyofFish','PlentyofFish'],['Christian Mingle','Christian Mingle'],['DateHookup','DateHookup'],['HowAboutWe','HowAboutWe'],['BlackPeopleMeet','BlackPeopleMeet'],['JDate','JDate'],['Skout','Skout'],['SeniorPeopleMeet','SeniorPeopleMeet']], { :prompt => 'Select'}, style: 'height:32px;') %>
		  </div>
		  <div class="field" style="width: 5%; display: inline-block;">
		  <%= f.hidden_field :_destroy %>
		  <%= link_to "remove", '#', class: "remove_fields" %>
	 	 </div>
	 </div>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div style="background: #fff; margin-top: 50px; margin-left: auto; margin-right: auto; width: 90%; padding: 40px; border-radius: 5px; box-shadow: 0 0 1px 1px;">

	<h1 style="margin-bottom: 0px;">Editing user</h1>
	


<%= render 'edit_form' %>


</div>
<div style="clear: both;"></div>
 

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User email</th>
      <th>User phone</th>
      <th>User handle</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_phone %></td>
        <td><%= user.user_handle %></td>
        <td><%= link_to 'Show', root_url+user.url_slug %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div style="background: #fff; margin-top: 50px; margin-left: auto; margin-right: auto; width: 90%; padding: 10px 15px 0 15px; border-radius: 5px; box-shadow: 0 0 1px 1px;">
	
	<!--	<p id="notice"><%= notice %></p> -->

	<div class="large-12" style="float: left; padding: 25px 10px 0 35px;">
		<% if @user.image? %>
			<div class="large-2" style="height:150px;width: 150px;float:left;margin-top:20px;"><%= image_tag @user.image_url(:thumb), style: "box-shadow: 0px 0px 0px 2.5px;"%></div>
			<% else %>

				<div class="large-2" style="height:150px;width: 150px;;float:left;margin-top:20px;"><%= image_tag('profile-picture-holder.png', style: "box-shadow: 0px 0px 0px 2.5px;") %></div>
			<% end %>


		<div class="large-4" style="float:left; clear:right;margin-right: 50px;">

		<h2 style="margin-bottom:0px; font-size:34px;"><%= @user.user_handle %></h2>

		<% if ! @user.profile_name_hidden? %>
		<p style="margin-bottom: 2px;">
		  <%= @user.first_name %> <%= @user.last_name %> 
		  </p>
	  <% end %>

	  <% if ! @user.hide_city_state? && ! @user.city.blank? && ! @user.state.blank? %>
		<p style="margin-bottom: 2px;">
		  <%= @user.city + ", "%><%= @user.state %>
		  </p>
	  <% end %>

  </div><br>

	  <div class="large-9" style="float: left;">
		  <p>
<% if @user.user_dating_usernames.count > 0 %>
	<% @user.user_dating_usernames.each do |name| %>
	<% if name == @user.user_dating_usernames.last %>
		<%= name.dating_site_website + ": " + name.dating_site_username %>
	<% else %>
		<%= name.dating_site_website + ": " + name.dating_site_username + " | " %>
	<% end %>
	<%end%>
<%end%>
</p>

	</div>
	
			<% if @user == current_user %> 
				<span style="float:left;clear:left; padding-right: 30px;"><%= link_to 'Edit Profile', edit_user_path(current_user), style: "float: right;margin-top:15px; margin-left:10px;" %></span>
			<% end %>
  	</div>


	<div style="clear: both;"></div>

	<% if @user == current_user %>

		<div class="large-11" style="margin: 0 auto; text-align: center; margin-top: 45px; /* border-bottom: dashed 2px #222; */ background: #28b779;padding: 15px;border-radius: 4px;font-color: #ffffff;text-overflow:ellipsis;overflow:hidden;overflow-wrap:break-word;">

					<h5 style="font-weight:normal;color: #fff;">This is your public profile where previous dates will be able to tell you what they thought. Share your profile with them or post it to your other online profiles.</h5>
					<h4 style="display:inline"> <a style="color: #ffb848;font-weight: bolder;font-size: 25px;" href=<%= root_url+@user.url_slug%>>lovememaybe/<%=@user.url_slug%></a></h4>
				</div>

				<% end %>



				<div id="response-area" class="large-11" style="margin: 0 auto; text-align: center; margin-top: 45px; padding-bottom:125px;">
					<%= render 'response_area' %>
	
	</div>



  </div>