config/routes.rb
LoveMaybe::Application.routes.draw do
  
  resources :friend_sayings

  resources :yes_sayings

  resources :date_responses

  resources :date_requests, only: [:create, :destroy, :edit, :update, :new]

  resources :user_dating_usernames

   get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  post 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/:provider/callback', to: 'sessions#create_FB'
  get 'auth/failure', to: redirect('/')

  delete '/signout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  get '/responses', to: 'welcome#response_tab'

  resources :users, except: [:show, :edit]

  resources :users, path: "", only: [:show, :edit]

  resources :sessions, only: [:new, :create, :destroy]	

  resources :password_resets

  resources :email_confirms

 

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if signed_in?
		  @user = current_user
		  @response_count = DateResponse.where("date_request_id > ? AND date_requester_id = ?", 0, @user.id).count
		  @request_count = DateRequest.where("user_id = ? AND matched = ?", @user.id, false).count
		end
		
	end

	def response_tab
		if signed_in?
		  @user = current_user
		  @request_count = DateRequest.where("user_id = ? AND matched = ?", @user.id, false).count

		  #getting date responses that match a date request previously made by user
		  @responses = DateResponse.where("date_request_id > ? AND date_requester_id = ?", 0, @user.id)
		  @response_count = @responses.count

		  #sorting responses into matches or anonymous responses
		  @matches = []
		  @anonymous_responses = []
		  @responses.each do |response|
			  request = DateRequest.find(response.date_request_id) if DateRequest.find(response.date_request_id)
			  if request.date_rating == response.date_response_rating && request.date_rating != 'No'
				  @matches << response
			  else
				  @anonymous_responses << response
			  end
		  end

		  @anonymous_min_response = 3
		else
			redirect_to root_path
		end
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_index.html.erb
<% if @user.date_requests.count > 0 %>
<div>
<table style="border: none; width: 100%;">
  <thead>
<tr style="background: #fff; font-size: 17px; text-decoration: underline;">
      <th style="padding-left:0px;">First Name</th>
      <th>Last Name</th>
      <th>Phone</th>
      <th>Dating Username</th>
      <th>Dating Site</th>
      <th style="text-align:center;">Rating</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.date_requests.where(matched: false).each do |date_request| %>
      <tr style="margin-right: 10px;" >
        <td style="margin-right: 10px; padding-left:0px;"><%= date_request.first_name %></td>
        <td style="margin-right: 10px;"><%= date_request.last_name.blank? ? "N/A" : date_request.last_name %></td>
        <td><%= date_request.date_phone.blank? ? "N/A" : date_request.date_phone %></td>
        <td><%= date_request.date_username.blank? ? "N/A" : date_request.date_username %></td>
        <td><%= date_request.date_username_site.blank? ? "N/A" : date_request.date_username_site %></td>
	<% if date_request.date_rating == "Yes" %>
			<td style="text-align:center;"><%= image_tag 'thumbup.png' %> </td>
		<% else %>
			<% if date_request.date_rating == "Friends" %>
		    		<td style="text-align:center;"><%= image_tag 'friendicon.png' %></td>
			<% else %>
				<td style="text-align:center;"><%= image_tag 'thumbdown.png' %></td>
			<% end %>
		<% end %>
	
        <td><%= link_to 'Delete', date_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>					
</div>

<% end %>


app/views/welcome/index.html.erb
<% provide(:title, 'LoveMeMaybe | Welcome!') %>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=609719912434364";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<style>.response-link { color: #ffffff; }
.response-link:hover { color: #ffffff; text-decoration: underline; }</style>

<% if signed_in? %>
			<%= render 'layouts/header' %>

			<div style="background: url(<%= asset_path 'background.png' %>) repeat; margin-top: 50px; margin-left: auto; margin-right: auto; width: 90%; border-radius: 5px; /*box-shadow: 0 0 1px 1px;*/">
			<div style="background: #FFFCDD; box-shadow: 0 0 1px 1px; border-bottom:none; width: 40%;height: 60px; border-radius: 5px 5px 0px 0px; margin-bottom: 0px; display: inline; float:left; padding: 20px; padding-left:5px;text-align: center;font-weight: 700; margin-right:25px;"><span style="background: url(<%= asset_path 'mini-heart.png' %>) no-repeat; padding:0px 0 5px 30px;">Requests (<%= @request_count %>)</span></div>
				<div style="width: 40%;height: 60px; clear:both; margin-bottom: 0px; display: inline-block; padding: 20px; text-align: center;"><%= link_to("Responses (#{@response_count})", {controller: :welcome, action: :response_tab}, {class: "response-link"}) %></div>

				<div style="width: 100%; background: #fff; border-radius: 0px 5px 5px 5px; margin-top:0px; padding: 50px 30px 30px 30px; box-shadow: 0 0 1px 1px;text-overflow:ellipsis;overflow:hidden;overflow-wrap:break-word;">

					  <% flash.each do |key, value| %>
	  <div class="flash-message-div large-8 alert alert-<%= key %>" style="background: #FFE48E;border: 1px solid;margin: 0 auto 25px auto;padding: 10px; text-align:center;"><%= value %><a id="close-flash" href="#" style="float: right;">X</a></div>
  <% end %>

  <div class="small-12" style="display: inline-block;border-radius: 5px;padding: 15px 15px 0px 20px;margin: 0 auto;text-align: center;">

	  <p style="font-style: italic; font-weight: 900; color:#fff; font-size:20px;color: #2795b6; margin-bottom:10px;">Post the below link to your dating &amp; social media profiles or send to date:</p>

						<div style="display: inline;margin: 0 auto;/* float: left; */">
							<%= image_tag('link-link.png') %>
						</div>
						<h5 style="margin-top:5px;"> <a style="color: #ffb848" href=<%= root_url+@user.url_slug%>>lovememaybe/<%= @user.url_slug%></a> </h5>
						<% if @user.date_requests.count <= 0 %>
							<h5 style="margin:20px;"> AND </h5>
							<%= link_to 'Add Date +', new_date_request_path, remote: :true, class: "button medium", id: "home-add-date-button" %>
						<% end %>
				</div>
					<div style="clear: both;"></div>
					<h4 style="margin-top: 60px; color: #444; font-size: 19px;"></h4>
					<div id="date_request_area"></div>
					
					<div id="request_area"><%= render 'index' %></div>
					<% if  @user.date_requests.count > 0 %>
						<%= link_to 'Add Date +', new_date_request_path, remote: :true, class: "button medium", id: "home-add-date-button" %>
					<% end %>
					
					
				</div>

</div>
<div style="clear: both;"></div>


		<% else %>

			<style> body {background: #ffffff!important;} </style>

			<div style="background: #eeeeee url(<%= asset_path 'background.png'%>) left top repeat; width: 100%; height: 300px; position: absolute; top: 0px; left:0px;"></div>


		<div class="large-12 columns" style="padding-top:15px; background: none;">
			<%= image_tag('home-logo.png') %>
			
			<% if signed_in? %>
				<%= link_to "Sign out", signout_path, method: "delete" %>
			<% else %>
				<a href=<%= signin_path%> class="button tiny alert" style="float: right;">Log In</a>
			<a href="<%= new_user_path%>" class="button tiny alert" style="float: right; margin-right: 10px;">Sign Up</a>
		<% end %>

		<div style:"clear:both;"></div>

   <% flash.each do |key, value| %>
	  <div class="flash-message-div large-8 alert alert-<%= key %>" style="background: #FFE48E;border: 1px solid;margin: 0 auto 25px auto;padding: 10px; text-align:center;"><%= value %><a id="close-flash" href="#" style="float: right;">X</a></div>
  <% end %>
		</div>

	<div class="large-12 columns" style="margin-top: 100px;">
		<div class="large-5 columns" style="margin-bottom: 15px;"><%= image_tag('home-app-menu.png') %></div>
		<div class="large-7 columns" style="float: right;padding-top:5px; height: 330px; background: #fff; box-shadow: 0 50px 0px 0px white, 0 -9px 0px 0px white, 6px 0 20px -10px rgba(0, 0, 0, 0.6), -6px 0 20px -10px rgba(0, 0, 0, 0.6); margin-top:8px;">
	  <h3 style="color: #003366;margin-bottom: 20px;">Find out how that date really went </h3>
	  <ol style="padding-left: 1.5em; line-height: 170%;">
		  <li style="margin-bottom: 10px;">Let your date know that you are into them if they are into you, or start a friendship without having to worry if they are interested in more</li>
		  <li style="margin-bottom: 10px;">Get &amp; give feedback <strong>without your date knowing it was you</strong></li>
		  <li>Use with any of the most popular online dating apps, and even get feedback from offline dates</li>
  </ol>
  <a style="margin-left: 1.5em;" href="/auth/facebook"><%=image_tag 'fcbk-signup.png', style: "margin-bottom:10px;", alt: "Facebook Signin" %></a><span style="margin: 0 0 0 10px;">or</span> 
	  <a style="margin-left:10px;" href="<%= new_user_path%>">Sign up with email</a>

    <div>
  <!--<div style="margin: 35px 1% 0 5%; display:inline-block; float:left;" class="fb-like" data-href='http://lovememaybe.co' data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
  <div style="margin: 35px 15% 0 5.5%; display:inline-block;float:left;"><a style="display:inline-block; float:left;" href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-url=#root_url  data-text="Find out how your date went with LoveMeMaybe" data-hashtags="SecondChances,FriendZone">Tweet</a></div> -->
  </div>
  
  
  </div>
  <div style:"clear:both;"></div>

 

  </div>

   

  <% end %>


app/views/welcome/response_tab.html.erb
<script>
$(document).ready(function() {
	$(".fancybox-link").fancybox({
		maxWidth	: 800,
		maxHeight	: 600,
		fitToView	: true,
		width		: '60%',
		height		: '60%',
		autoSize	: true,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});
	
  </script>

<style>.request-link { color: #ffffff; }
	.request-link:hover { color: #ffffff; text-decoration: underline; }</style>

			<%= render 'layouts/header' %>

			<div style="background: url(<%= asset_path 'background.png' %>) repeat; margin-top: 50px; margin-left: auto; margin-right: auto; width: 90%; border-radius: 5px; /*box-shadow: 0 0 1px 1px;*/">
				<div style="width: 40%;height: 60px; border-radius: 5px 5px 0px 0px; margin-bottom: 0px; display: inline; float:left; padding: 20px; text-align: center;"><%= link_to "Requests (#{@request_count})", root_path, class: "request-link" %></div>
				<div style="width: 40%;height: 60px; clear:both; margin-bottom: 0px; display: inline-block; padding: 20px; padding-left: 5px;text-align: center;background: #FFFCDD; box-shadow: 0 0 1px 1px; border-bottom:none; border-radius: 5px 5px 0px 0px;font-weight: 700;"><span style="background: url(<%= asset_path 'mini-heart.png' %>) no-repeat; padding:0px 0 5px 30px;">Responses (<%= @response_count %>)</span></div>

				<div style="width: 100%; background: #fff; border-radius: 5px 5px 5px 5px; margin-top:0px; padding: 30px 30px 30px 30px; box-shadow: 0 0 1px 1px;text-overflow:ellipsis;overflow:hidden;overflow-wrap:break-word;">
					<div class="small-12" style="display: inline-block;border-radius: 5px;padding: 15px 15px 0px 0px;margin: 0 auto;">
					<div style="display: inline;margin: 0 auto;/* float: left; */">
							<%= image_tag('link-link.png', style: "float: left;") %>
						</div>
						<h5 style="margin-top:5px;"> <a style="color: #ffb848" href=<%= root_url+@user.url_slug%>>lovememaybe/<%= @user.url_slug%></a> </h5></div>
					<div style="clear: both;"></div>
					<h4 style="margin-top: 30px; color: #444; font-size: 19px;">Matches</h4>
					<% if @matches.empty?  %>

						<h6 style="font-weight:300;">You currently have no matches. <%= link_to 'Create a new date request', root_path %> or share your profile link to find out if your date was into you! </h6>

					<% else %>


				<table style="border: none; width: 100%;">
  <thead>
<tr style="background: #fff; font-size: 17px; text-decoration: underline;">
      <th>First Name</th>
      <th>Phone</th>
      <th>Dating Username</th>
      <th>Dating Site</th>
      <th style="text-align:center;">Rating</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	  <% @matches.each do |match| %>
		  <% @date_request = DateRequest.find(match.date_request_id) %>
      <tr style="margin-right: 10px;" >
        <td style="margin-right: 10px;"><%= @date_request.first_name %></td>
        <td><%= @date_request.date_phone %></td>
        <td><%= @date_request.date_username.blank? ? "N/A" : @date_request.date_username %></td>
        <td><%= @date_request.date_username_site.blank? ? "N/A" : @date_request.date_username_site  %></td>
	<% if @date_request.date_rating == "Yes" %>
			<td style="text-align:center;"><%= image_tag 'thumbup.png' %> </td>
		<% else %>
			<% if @date_request.date_rating == "Friends" %>
		    		<td style="text-align:center;"><%= image_tag 'friendicon.png' %></td>
			<% else %>
				<td style="text-align:center;"><%= image_tag 'thumbdown.png' %></td>
			<% end %>
		<% end %>
		<td><%= link_to "View", "#inline#{match.id}", remote: :true, class: "fancybox-link" %></td>
		<div id="inline<%= match.id%>" class="large-11" style="margin: 0 auto; text-align: center; margin-top: 45px; padding-bottom:125px; display:none;">
			<h3 style="margin-bottom: 40px;">You and <%=@date_request.first_name%> both want to <%= @date_request.date_rating == 'Yes' ? 'go on another date!' : 'be friends!' %></h3>
			<h5 style="font-weight: 300;">What <%= @date_request.first_name %> said about you:</h5>
			<h5 style="color: #2795b6; font-style: italic;margin-bottom: 40px;"><%= match.date_response_comment %></h5>
			<h3 style="margin-bottom: 40px;"><%= @date_request.date_rating == 'Yes' ? YesSaying.first(offset: rand(YesSaying.count)).saying : FriendSaying.first(offset: rand(FriendSaying.count)).saying %></h3>
		</div>
</tr>
    <% end %>
  </tbody>
</table>

<% end %>

					<div style="clear: both;"></div>
				
					<% if @anonymous_responses.count < @anonymous_min_response %>
						<h4 style="margin-top: 40px; color: #444; font-size: 19px;">Anonymous Responses</h4>
						<h6 style="font-weight:300;">Responses from dates who are not matches are anonymous. You need <span style="font-weight: 700; text-decoration: underline;"><%= @anonymous_min_response - @anonymous_responses.count %></span> more <%= @anonymous_min_response - @anonymous_responses.count > 1 ? 'responses' : 'response' %> to view anonymous feedback.</h6>
					<% else %>

<table style="border: none; width: 45%;">
  <thead>
<tr style="background: #fff; margin-top: 40px; color: #444; font-size: 19px;">
      <th style="padding: 0 0 20px 0; margin-top: 20px; color: #444; font-size: 19px;">Anonymous Responses</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	  <% @anonymous_responses.each do |ar| %>
		  <% @date_request = DateRequest.find(ar.date_request_id) %>
      <tr style="margin-right: 10px;" >
        <td style="margin-right: 10px;"><%= truncate(ar.date_response_comment, length: 25, separator: ' ') %></td>
	<td><%= link_to 'View Comment', "#inline#{ar.id}", remote: :true,  class: "fancybox-link" %></td>

	<div id="inline<%=ar.id%>" style="display:none; padding:50px;"><h4>Anonymous Feedback</h4><h5 style="color: #2795b6;font-style: italic;"><%=ar.date_response_comment%></h5></div>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>
				
					<div id="date_request_area"></div>
					
				</div>

</div>
<div style="clear: both;"></div>